# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/jayeliu"

[social.params]
icon = "brand-github"

[[social]]
identifier = "xlog"
name = "XLog"
url = "https://jaeliu-6268.xlog.app/"

[social.params]
icon = "xlog"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://bilibili.com"

[social.params]
icon = "brand-bilibili"

